-- ============================================================
-- HELM Academy — Library Resources Seed Data
-- Source: data/library.ts → MOCK_LIBRARY (16 records)
-- Run AFTER schema.sql in the Supabase SQL Editor
-- ============================================================

INSERT INTO library_resources (
    id,
    title,
    author,
    year,
    type,
    category,
    description,
    page_count,
    language,
    is_premium,
    rating,
    reviews_count,
    cover_image,
    cover_gradient,
    download_count,
    added_at,
    is_featured,
    file_url
) VALUES

-- ── Books (6) ─────────────────────────────────────────────────

(
    'res_bk_01',
    'Applied Drilling Engineering',
    'Adam T. Bourgoyne Jr., et al.',
    1986,
    'Book',
    'Drilling',
    'An industry standard for drilling professionals, covering basic principles, drilling fluids, cementing, and advanced drilling operations.',
    502,
    'EN',
    true,
    4.9,
    1542,
    NULL,
    'from-orange-700 via-orange-900 to-black',
    45000,
    '2023-01-15T00:00:00Z',
    true,
    NULL
),
(
    'res_bk_02',
    'Petroleum Reservoir Engineering Practice',
    'Nnaemeka Ezekwe',
    2011,
    'Book',
    'Reservoir',
    'A comprehensive guide to practical reservoir engineering, material balance, and decline curve analysis.',
    384,
    'EN',
    true,
    4.8,
    890,
    NULL,
    'from-teal-800 via-teal-950 to-black',
    32000,
    '2023-03-10T00:00:00Z',
    true,
    NULL
),
(
    'res_bk_03',
    'Production Optimization Using NODAL Analysis',
    'H. Dale Beggs',
    2003,
    'Book',
    'Production',
    'Essential text for optimizing well and flowline performance using nodal analysis techniques.',
    411,
    'EN',
    false,
    4.7,
    620,
    NULL,
    'from-blue-700 via-blue-900 to-black',
    28000,
    '2023-05-22T00:00:00Z',
    false,
    NULL
),
(
    'res_bk_04',
    'هندسة الحفر المتقدمة',
    'د. طارق الحسين',
    2021,
    'Book',
    'Drilling',
    'كتاب شامل يغطي أحدث التطورات في هندسة الحفر، بما في ذلك الحفر الموجه وأنظمة التوجيه الدوارة.',
    320,
    'AR',
    true,
    4.9,
    415,
    NULL,
    'from-red-800 via-orange-950 to-black',
    15000,
    '2023-06-05T00:00:00Z',
    true,
    NULL
),
(
    'res_bk_05',
    'L''ingénierie des Réservoirs Fracturés',
    'Alain Gringarten',
    2018,
    'Book',
    'Reservoir',
    'Une approche moderne pour la caractérisation et la simulation des réservoirs naturellement fracturés.',
    450,
    'FR',
    true,
    4.6,
    210,
    NULL,
    'from-purple-800 via-indigo-950 to-black',
    9500,
    '2023-07-12T00:00:00Z',
    false,
    NULL
),
(
    'res_bk_06',
    'Fundamentals of Petroleum Economics',
    'Chris T.',
    2020,
    'Book',
    'Economics',
    'Decision making models, risk analysis, and fiscal systems in the modern oil and gas industry.',
    280,
    'EN',
    false,
    4.5,
    340,
    NULL,
    'from-yellow-700 via-yellow-900 to-black',
    12000,
    '2023-08-01T00:00:00Z',
    false,
    NULL
),

-- ── Research Papers (4) ───────────────────────────────────────

(
    'res_rp_01',
    'Machine Learning Applications in Well Log Interpretation',
    'SPE International Journal',
    2023,
    'Research Paper',
    'Reservoir',
    'A novel approach utilizing deep learning neural networks to predict rock properties from standard wireline logs.',
    24,
    'EN',
    false,
    4.8,
    156,
    'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&q=80&w=400',
    NULL,
    4500,
    '2024-01-15T00:00:00Z',
    false,
    NULL
),
(
    'res_rp_02',
    'Advances in MWD Telemetry Systems',
    'Journal of Petroleum Technology',
    2022,
    'Research Paper',
    'Drilling',
    'Comparison of high-speed mud pulse, electromagnetic, and wired drill pipe telemetry methods.',
    18,
    'EN',
    true,
    4.7,
    89,
    NULL,
    NULL,
    3200,
    '2023-11-20T00:00:00Z',
    false,
    NULL
),
(
    'res_rp_03',
    'تقييم مخاطر السلامة في المنصات البحرية',
    'مجلة هندسة النفط العربية',
    2023,
    'Research Paper',
    'HSE',
    'دراسة تحليلية شاملة لحوادث المنصات البحرية وتطوير نموذج تقييم المخاطر الكمي.',
    32,
    'AR',
    false,
    4.9,
    210,
    NULL,
    NULL,
    5600,
    '2024-02-10T00:00:00Z',
    true,
    NULL
),
(
    'res_rp_04',
    'Optimisation de la Chaîne Logistique du GNL',
    'Revue de l''Energie',
    2021,
    'Research Paper',
    'LNG',
    'Modèles mathématiques pour la réduction des coûts de transport et de regazéification du Gaz Naturel Liquéfié.',
    22,
    'FR',
    true,
    4.4,
    75,
    NULL,
    NULL,
    1800,
    '2023-09-05T00:00:00Z',
    false,
    NULL
),

-- ── Summaries (3) ─────────────────────────────────────────────

(
    'res_sm_01',
    'Summary: Well Control & Blowout Prevention',
    'HELM Academic Team',
    2024,
    'Summary',
    'HSE',
    'A quick-reference guide summarizing IWCF Level 4 concepts, calculations, and kill sheets.',
    15,
    'EN',
    false,
    4.9,
    850,
    NULL,
    'from-green-600 to-emerald-900',
    18000,
    '2024-03-01T00:00:00Z',
    false,
    NULL
),
(
    'res_sm_02',
    'ملخص قوانين هندسة الإنتاج',
    'HELM Academic Team',
    2023,
    'Summary',
    'Production',
    'تجميع لأهم القوانين والمعادلات المستخدمة في هندسة الإنتاج وتصميم الرفع الصناعي.',
    20,
    'AR',
    false,
    4.8,
    640,
    NULL,
    'from-blue-600 to-indigo-900',
    14500,
    '2023-12-15T00:00:00Z',
    false,
    NULL
),
(
    'res_sm_03',
    'Quick Guide to Eclipse Keywords',
    'HELM Academic Team',
    2023,
    'Summary',
    'Reservoir',
    'A comprehensive cheat sheet for the most commonly used Eclipse reservoir simulation scheduler keywords.',
    12,
    'EN',
    true,
    4.7,
    420,
    NULL,
    'from-teal-600 to-cyan-900',
    8900,
    '2023-10-22T00:00:00Z',
    false,
    NULL
),

-- ── Graduation Projects (3) ───────────────────────────────────

(
    'res_gp_01',
    'Design of a Multi-Lateral Well in Carbonate Reservoir',
    'Univ. of Boumerdès (UMBB) Alumni',
    2022,
    'Graduation Project',
    'Drilling',
    'A detailed engineering design project for a level 4 multilateral well aiming to increase contact area in a tight carbonate formation.',
    120,
    'EN',
    false,
    4.6,
    110,
    'https://images.unsplash.com/photo-1541888040210-90ee4df3e574?auto=format&fit=crop&q=80&w=400',
    NULL,
    2100,
    '2023-02-10T00:00:00Z',
    false,
    NULL
),
(
    'res_gp_02',
    'دراسة الجدوى الاقتصادية لمشروع استخلاص معزز للنفط (CO2 EOR)',
    'KSU Petroleum Department',
    2023,
    'Graduation Project',
    'Economics',
    'نمذجة اقتصادية متكاملة لتقييم ربحية مشروع حقن غاز ثاني أكسيد الكربون في حقل ناضج.',
    95,
    'AR',
    true,
    4.8,
    145,
    NULL,
    NULL,
    3400,
    '2024-01-25T00:00:00Z',
    false,
    NULL
),
(
    'res_gp_03',
    'Conception d''une Unité de Séparation Triphasique',
    'USTHB Engineering',
    2021,
    'Graduation Project',
    'Production',
    'Dimensionnement et simulation d''un séparateur triphasique pour un champ gazier utilisant HYSYS.',
    105,
    'FR',
    false,
    4.5,
    85,
    'https://images.unsplash.com/photo-1620325867502-221ddb5faa5f?auto=format&fit=crop&q=80&w=400',
    NULL,
    1900,
    '2023-04-18T00:00:00Z',
    false,
    NULL
);
